name: test-action
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 build:
    name: test
    runs-on: ubuntu-18.04
    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
    steps:
      run: ls -R

