name: test-action
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
    steps:
      run: ls -R

